---
title: "Homework 2"
author: "Yige Bian (yb2591)"
date: 2023-10-01
output: github_document
---

```{r setup, include = FALSE}
Sys.setenv(LANG = "en_US")
library(tidyverse)
```

```{r tidy ppols_month}
# Import data "pol-month" and define types of columns. Warning: There are several '2' in column 'prez_gop' which should be treated the same as '1'.  Then, break up the variable 'mon', replace month number with month name, create 'president' variable, remove 'prez_dem' and 'prez_gop' and 'day'

pols_month = 
  read_csv("./data/pols-month.csv", col_types = "Dliiiliii") |>
  janitor::clean_names() |>
  mutate(prez_gop = replace(prez_gop, is.na(prez_gop), TRUE)) |>
  separate(mon, into = c("year","month","day"), sep = "-") |>
  mutate(
    month = 
      case_match(
        month,
        "01" ~ "January",
        "02" ~ "February",
        "03" ~ "March",
        "04" ~ "April",
        "05" ~ "May",
        "06" ~ "June",
        "07" ~ "July",
        "08" ~ "August",
        "09" ~ "September",
        "10" ~ "October",
        "11" ~ "November",
        "12" ~ "December"),
    president = case_match(
        prez_gop,
        TRUE ~ "gop",
        FALSE ~ "dem")) |>
  select(-prez_dem,-prez_gop,-day)
```
```{r tidy snp}
# Import and clean data snp 
snp = 
  read_csv("./data/snp.csv", col_types = cols(date = col_date("%m/%d/%y"))) |>
  janitor::clean_names() |>
  separate(date, into = c("year","month","day"), sep = "-") |>
  mutate(
    year = 
      as.character(ifelse(as.numeric(year) >= 2050, as.numeric(year)-100, as.numeric(year)))) |>
  arrange(year, month) |>
  select(year, month, everything()) |>
  mutate(
    month = 
      case_match(
        month,
        "01" ~ "January",
        "02" ~ "February",
        "03" ~ "March",
        "04" ~ "April",
        "05" ~ "May",
        "06" ~ "June",
        "07" ~ "July",
        "08" ~ "August",
        "09" ~ "September",
        "10" ~ "October",
        "11" ~ "November",
        "12" ~ "December"))
```

```{r tidy unemployment}
# Import data unemployment and swith from wide to long format. 
unemployment =
  read_csv("./data/unemployment.csv", col_types = "cd") |>
  janitor::clean_names() |>
  pivot_longer(jan:dec,
               names_to = "month",
               values_to = "per_of_unemp") |>
  mutate(
    month = 
      case_match(
        month,
        "jan" ~ "January",
        "feb" ~ "February",
        "mar" ~ "March",
        "apr" ~ "April",
        "may" ~ "May",
        "jun" ~ "June",
        "jul" ~ "July",
        "aug" ~ "August",
        "sep" ~ "September",
        "oct" ~ "October",
        "nov" ~ "November",
        "dec" ~ "December"))
```

```{r merge pols_month, snp and unemployment}
merge_data = 
  left_join(pols_month, snp, by = c("year","month")) |>
  left_join(unemployment, by = c("year","month"))
```

